#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SyscallId {
    // Linux i386 int 0x80 numbers for the syscalls with matching ABI.
    Exit = 1,
    Fork = 2,
    Read = 3,
    Write = 4,
    Open = 5,
    Close = 6,
    WaitPid = 7,
    Execve = 11,
    Lseek = 19,
    GetPid = 20,
    Pipe = 42,
    Ioctl = 54,
    GetPpid = 64,
    Fstat = 108,
    // PolyOS-private calls live in the high u8 range to avoid Unix collisions.
    Sleep = 200,
    Malloc = 201,
    Free = 202,
    PrintMemory = 203,
    Reboot = 204,
    Shutdown = 205,
    NetworkInfo = 220,
    NetworkDhcpDiscover = 221,
    NetworkPingGateway = 222,
    NetworkPingIpv4 = 223,
    NetworkDnsQuery = 224,
    NetworkPingName = 225,
    NetworkSocket = 226,
    NetworkSendTo = 227,
    NetworkRecvFrom = 228,
    NetworkRecvFromWait = 229,
    SemaphoreCreate = 230,
    SemaphoreWait = 231,
    SemaphoreSignal = 232,
    SemaphoreClose = 233,
}

impl SyscallId {
    pub const fn new(v: u8) -> Option<Self> {
        match v {
            1 => Some(Self::Exit),
            2 => Some(Self::Fork),
            3 => Some(Self::Read),
            4 => Some(Self::Write),
            5 => Some(Self::Open),
            6 => Some(Self::Close),
            7 => Some(Self::WaitPid),
            11 => Some(Self::Execve),
            19 => Some(Self::Lseek),
            20 => Some(Self::GetPid),
            42 => Some(Self::Pipe),
            54 => Some(Self::Ioctl),
            64 => Some(Self::GetPpid),
            108 => Some(Self::Fstat),
            200 => Some(Self::Sleep),
            201 => Some(Self::Malloc),
            202 => Some(Self::Free),
            203 => Some(Self::PrintMemory),
            204 => Some(Self::Reboot),
            205 => Some(Self::Shutdown),
            220 => Some(Self::NetworkInfo),
            221 => Some(Self::NetworkDhcpDiscover),
            222 => Some(Self::NetworkPingGateway),
            223 => Some(Self::NetworkPingIpv4),
            224 => Some(Self::NetworkDnsQuery),
            225 => Some(Self::NetworkPingName),
            226 => Some(Self::NetworkSocket),
            227 => Some(Self::NetworkSendTo),
            228 => Some(Self::NetworkRecvFrom),
            229 => Some(Self::NetworkRecvFromWait),
            230 => Some(Self::SemaphoreCreate),
            231 => Some(Self::SemaphoreWait),
            232 => Some(Self::SemaphoreSignal),
            233 => Some(Self::SemaphoreClose),
            _ => None,
        }
    }
}
