[package]
name = "rust_kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
bindgen = "0.71.0"
walkdir = "2.3"

[dependencies]
bitflags = "2.8.0"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
linked_list_allocator = "0.10.5"
spin = "0.9.8"
uart_16550 = "0.3.2"

[profile.release]
panic = "abort"
lto = true
codegen-units = 3
