[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"

[dependencies]
polyos_std = { path = "../polyos_std" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 3
