[unstable]
# This feature requires nightly and will build the 'core' and 'alloc' crates for your custom target.
build-std = ["core", "alloc", "compiler_builtins"]

[build]
target = "i686-custom.json"

[target.i686-custom]
rustflags = [
    "-C", "relocation-model=static"
]